apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp

spec:
  #minReadySeconds: 30
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      #name: webapp
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue

spec:
  #minReadySeconds: 30
  replicas: 1
  selector:
    matchLabels:
      app: queue
  template:
    metadata:
      #name: webapp
      labels:
        app: queue
    spec:
      containers:
      - name: queue
        image: richardchesterwood/k8s-fleetman-queue:release1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pos-simulator

spec:
  #minReadySeconds: 30
  replicas: 1
  selector:
    matchLabels:
      app: pos-simulator
  template:
    metadata:
      #name: webapp
      labels:
        app: pos-simulator
    spec:
      containers:
      - name: pos-simulator
        image: richardchesterwood/k8s-fleetman-position-simulator:release1
        env: 
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice